
- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Atlas
  - Amber
  - Bagel
  - Box
  - MiniSilly
  - MiniCluster
  #- Core
  - Fland
 # - Gate Goobstation - My name is Walter Hartwell White, I live at 2308 Negra alloya line albequrque new mexico.
  #- Loop Goobstation - I love maintenance!!!
  - Marathon
  - Meta
  - Oasis
  - MiniOmega
  - Origin
  # - Saltern
  - MiniPacked
  #- Reach # Goobstation, removed from map pool
  #- Train # Goobstation - all my friends hate train
  - FlandHighPop
  - OasisHighPop
  - Barratry # Goobstation - Re-add barratry
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  - Submarine # goobstation - kill yourse
  - Leonid # Goobstation - for goob by goob
  - Delta # Goobstation - ported from Corvax
  - Chloris # Goobstation - also Corvax because we love goidamaps
  - Cog # those who forget to clear their multitool
  - Serpentcrest # Goobstation when contra
